name: OpenWrt Actions

on:
  repository_dispatch:
    release:
      types: published
    push:
      branches:
        - main
      paths:
        - 'config.seed'
    schedule:
      - cron: 0 8 * * *
    watch:
      types: started

env:
  REPO_URL: 
  REPO_BRANCH:
  CONFIG_FILE:
  BEFORE_SCRIPT: scripts/before_script.sh
  BEFORE_INSTALL: 
  AFTER_INSTALL:
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true 
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          ./$BEFORE_SCRIPT
