#!/bin/sh /etc/rc.common
#https://github.com/1phalley/smartdnsprocd

START=99
USE_PROCD=1

SMARTDNS="/etc/init.d/smartdns start"

#start_service 函数必须要重新定义
start_service() {
    #创建一个实例,在procd看来一个应用程序可以多个实例
    #ubus call service list 可以查看实例
    procd_open_instance
    
    #定义respawn参数, 告知procd当Smartdns程序退出后尝试进行重启
    procd_set_param respawn
    
    #执行Smartdns启动命令
    procd_set_param command "$SMARTDNS"

    #关闭实例
    procd_close_instance
}

#stop_service重新定义,退出服务器后需要做的操作
stop_service() {
rm -f /var/run/smartdns.pid
}

restart() {
stop
start
}