#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.Knowhere >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.Knowhere=/luci-static/knowhere
		set luci.main.mediaurlbase=/luci-static/knowhere
		commit luci
	EOF
fi

exit 0
