#!/bin/sh

ln -sf /sbin/ip /usr/bin/ip

sed -i '/openwrt_custom/d' /etc/opkg/distfeeds.conf
sed -i '/openwrt_custom/d' /etc/opkg/customfeeds.conf
sed -i '/openwrt_packages2/d' /etc/opkg/customfeeds.conf
sed -i 's/downloads.openwrt.org/op.supes.top/g' /etc/opkg/distfeeds.conf

sed -i 's/http:/https:/g' /etc/opkg/distfeeds.conf
sed -i "s/# //g" /etc/opkg/distfeeds.conf
grep -q log-facility /etc/dnsmasq.conf ||
	echo "log-facility=/dev/null" >> /etc/dnsmasq.conf
grep -q /etc/dnsmasq.d /etc/dnsmasq.conf ||
	echo "conf-dir=/etc/dnsmasq.d" >> /etc/dnsmasq.conf

sed -i '/profile.d/d' /lib/upgrade/keep.d/base-files
sed -i 's/\[ -e "$FILE" \] && . "$FILE"/[ -e "$FILE" ] \&\& env -i bash "$FILE"/g' /etc/profile

rm -rf /tmp/luci-*

sed -i '/S99opkg/d' /etc/crontabs/root
echo "0 0 */3 * * sh /etc/rc.d/S99opkg >/dev/null 2>&1" >> /etc/crontabs/root

grep -q adblock /etc/crontabs/root ||
	echo "00 00 * * * /etc/init.d/adblock reload" >> /etc/crontabs/root

uci set system.@rngd[0].enabled="1"
uci commit system

uci set uhttpd.main.rfc1918_filter=0
uci set uhttpd.main.redirect_https=0
uci commit uhttpd

if [ ! -f /etc/config/placeholder ]; then

	if [ $(uci get network.wan.ipv6) == 0 ]; then
			uci set dhcp.@dnsmasq[0].filter_aaaa='1'
			uci commit dhcp
	else
		uci set dhcp.@dnsmasq[0].filter_aaaa='0'
		uci commit dhcp
		uci set turboacc.config.sfe_ipv6='1'
		uci commit turboacc
	fi

  uci set luci.main.lang=auto
  uci set luci.main.mediaurlbase=/luci-static/edge
  uci commit luci
  
  uci set system.@system[0].timezone=CST-8
  uci set system.@system[0].zonename=Asia/Shanghai
  uci commit system

  uci set fstab.@global[0].anon_mount=1
  uci commit fstab
  
  sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
  
  uci set network.lan.ipaddr="192.168.77.1"
  uci set network.wan.proto=static
  uci set network.wan.ipaddr=192.168.1.7
  uci set network.wan.netmask=255.255.255.0
  uci set network.wan.gateway=192.168.1.1
  uci set network.wan.dns='114.114.114.114 8.8.4.4'
  uci commit network

  uci set network.@globals[0].packet_steering=1
  uci commit network
  
  uci set dhcp.@dnsmasq[0].dns_redirect='1'
  uci set dhcp.dnsmasq[0].allservers='1'
  uci set dhcp.lan.force='1'
  uci commit dhcp

fi

cp -R /www/cgi-bin/* /www/
find /www -type d -exec chmod 755 {} \;
chmod +x /www/luci

sed -i "s/git-.*-\(.*\)/git-\1/g" /usr/lib/lua/luci/version.lua

grep -q reboot /etc/shinit ||
	sed -i '$a alias reboot="(/sbin/reboot &);sleep 3;/sbin/reboot -f"\nalias /sbin/reboot="(/sbin/reboot &);sleep 3;/sbin/reboot -f"' /etc/shinit

ln -s /sbin/poweroff /sbin/shutdown
