#!/bin/sh



uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci set system.@system[0].hostname=x86
uci commit system


uci set network.lan.dns="114.114.114.114"
#uci set network.lan.delegate="0"
uci set network.lan.ipaddr='192.168.77.1'
uci set network.lan.proto='static'
uci set network.lan.type='bridge'
#uci set network.lan.ifname='eth0'
#uci set network.wan.ifname='eth1'
uci set network.wan.peerdns="0"
uci set network.wan.dns="114.114.114.114"
uci set network.wan6.peerdns="0"
uci set network.wan6.dns="::1 2001:4860:4860::8888"
uci commit network


ln -sf /sbin/ip /usr/bin/ip

sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

sed -i 's#https://downloads.openwrt.org#https://mirrors.cloud.tencent.com/lede#g' /etc/opkg/distfeeds.conf

sed -i '/REDIRECT --to-ports 53/d' /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p udp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user
echo "iptables -t nat -A PREROUTING -p tcp --dport 53 -j REDIRECT --to-ports 53" >> /etc/firewall.user


sed -i '/log-facility/d' /etc/dnsmasq.conf
echo "log-facility=/dev/null" >> /etc/dnsmasq.conf

sed -i 's/cbi.submit\"] = true/cbi.submit\"] = \"1\"/g' /usr/lib/lua/luci/dispatcher.lua

sed -i 's/limit-as = 1000/limit-as = 10000/g' /etc/uwsgi/vassals/luci-webui.ini

echo 'hsts=0' > /root/.wgetrc

rm -rf /tmp/luci-modulecache/
rm -f /tmp/luci-indexcache

exit 0