name: OpenWrt Actions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REPO_URL: https://github.com/1nfsr/openwrt.git
  REPO_BRANCH: main
  CONFIG_FILE:
  BEFORE_SCRIPT: scripts/before_script.sh
  BEFORE_INSTALL: 
  AFTER_INSTALL:
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@v2

      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          echo "hello"

      - name: Clone Source
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: Update&Install feeds
        working-directory: ./openwrt
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a


