# This is a basic workflow to help you get started with Actions

name: OpenWrt Actions

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REPO_URL: 
  REPO_BRANCH:
  CONFIG_FILE:
  BEFORE_SCRIPT: scripts/before_script.sh
  BEFORE_INSTALL: 
  AFTER_INSTALL:
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  UPLOAD_WETRANSFER: true
  UPLOAD_RELEASE: true 
  TZ: Asia/Shanghai

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          chmod +x ./scripts/*.sh
          ./$BEFORE_SCRIPT
