port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: silent
external-controller: :9090
proxies:
  - {name: "[VMess] 日本1-V2Ray", server: jp01-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp01-vm0.entry.ikuuu.casa}, udp: true}
  - {name: "[VMess] 日本2-V2Ray", server: jp02-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp02-vm0.entry.ikuuu.casa}, udp: true}
  - {name: "[VMess] 日本3-V2Ray", server: jp03-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp03-vm0.entry.ikuuu.casa}, udp: true}
  - {name: "[VMess] 日本4-V2Ray", server: jp04-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp04-vm0.entry.ikuuu.casa}, udp: true}
  - {name: "[VMess] 日本5-V2Ray", server: jp05-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp05-vm0.entry.ikuuu.casa}, udp: true}
  - {name: "[VMess] 日本6-V2Ray", server: jp06-vm0.entry.ikuuu.casa, port: 446, type: vmess, uuid: d5416287-2eae-3fd7-99a0-cdc8d399347a, alterId: 1, cipher: auto, tls: false, skip-cert-verify: false, network: ws, ws-path: /hls/cctv5phd.m3u8, ws-headers: {Host: jp06-vm0.entry.ikuuu.casa}, udp: true}
proxy-groups:
  - name: Proxies
    type: select
    proxies:
      - 自动选择
      - 故障转移
      - 负载均衡
      - "[VMess] 日本1-V2Ray"
      - "[VMess] 日本2-V2Ray"
      - "[VMess] 日本3-V2Ray"
      - "[VMess] 日本4-V2Ray"
      - "[VMess] 日本5-V2Ray"
      - "[VMess] 日本6-V2Ray"

  - name: 自动选择
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - "[VMess] 日本1-V2Ray"
      - "[VMess] 日本2-V2Ray"
      - "[VMess] 日本3-V2Ray"
      - "[VMess] 日本4-V2Ray"
      - "[VMess] 日本5-V2Ray"
      - "[VMess] 日本6-V2Ray"

  - name: 故障转移
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 180
    proxies:
      - "[VMess] 日本1-V2Ray"
      - "[VMess] 日本2-V2Ray"
      - "[VMess] 日本3-V2Ray"
      - "[VMess] 日本4-V2Ray"
      - "[VMess] 日本5-V2Ray"
      - "[VMess] 日本6-V2Ray"

  - name: 负载均衡
    type: load-balance
    url: http://www.gstatic.com/generate_204
    interval: 180
    proxies:
      - "[VMess] 日本1-V2Ray"
      - "[VMess] 日本2-V2Ray"
      - "[VMess] 日本3-V2Ray"
      - "[VMess] 日本4-V2Ray"
      - "[VMess] 日本5-V2Ray"
      - "[VMess] 日本6-V2Ray"

rules:
 # 抗 DNS 污染 
 - DOMAIN-KEYWORD,amazon,Proxies
 - DOMAIN-KEYWORD,google,Proxies
 - DOMAIN-KEYWORD,gmail,Proxies
 - DOMAIN-KEYWORD,youtube,Proxies
 - DOMAIN-KEYWORD,facebook,Proxies
 - DOMAIN-SUFFIX,fb.me,Proxies
 - DOMAIN-SUFFIX,fbcdn.net,Proxies
 - DOMAIN-KEYWORD,twitter,Proxies
 - DOMAIN-KEYWORD,instagram,Proxies
 - DOMAIN-KEYWORD,dropbox,Proxies
 - DOMAIN-SUFFIX,twimg.com,Proxies
 - DOMAIN-KEYWORD,blogspot,Proxies
 - DOMAIN-SUFFIX,youtu.be,Proxies
 - DOMAIN-KEYWORD,whatsapp,Proxies
 # LAN
 - DOMAIN-SUFFIX,local,DIRECT
 - IP-CIDR,127.0.0.0/8,DIRECT
 - IP-CIDR,172.16.0.0/12,DIRECT
 - IP-CIDR,192.168.0.0/16,DIRECT
 - IP-CIDR,10.0.0.0/8,DIRECT
 - IP-CIDR,17.0.0.0/8,DIRECT
 - IP-CIDR,100.64.0.0/10,DIRECT
 # 最终规则
 - GEOIP,CN,DIRECT
 - MATCH,Proxies

#系统代理绕过域名或地址，参考 绕过系统代理
cfw-bypass:
 - 'music.163.com' # 网易云域名1
 - '*.music.126.net' # 网易云域名2